<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RazorCompileOnBuild Condition="'$(CONFIG)'!='Debug'">true</RazorCompileOnBuild>
        <RazorCompiledOnPublish Condition="'$(CONFIG)'!='Debug'">true</RazorCompiledOnPublish>
        <PreserveCompilationContext>false</PreserveCompilationContext>
        <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>

        <Version>0.1.0.0</Version>
        <Configurations>Debug;Release;Prerelease</Configurations>
        <LangVersion>Latest</LangVersion>
        <ApplicationIcon/>
        <OutputType>Library</OutputType>
        <StartupObject/>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\SharedLibraryCore\SharedLibraryCore.csproj" />
        <ProjectReference Include="..\..\Integrations\SevenDaysToDie\Integrations.SevenDaysToDie.csproj" />
    </ItemGroup>

</Project>
