<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Authors>MrAmos123</Authors>
        <OutputType>Library</OutputType>
        <Configurations>Debug;Release;Prerelease</Configurations>
        <Platforms>AnyCPU</Platforms>
        <RootNamespace>IW4MAdmin.Plugins.Mute</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\SharedLibraryCore\SharedLibraryCore.csproj" PrivateAssets="All" Private="false" />
        <ProjectReference Include="..\..\Data\Data.csproj" PrivateAssets="All" Private="false" />
    </ItemGroup>

</Project>
