<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Authors>MrAmos123</Authors>
        <OutputType>Library</OutputType>
        <Configurations>Debug;Release;Prerelease</Configurations>
        <Platforms>AnyCPU</Platforms>
        <RootNamespace>IW4MAdmin.Plugins.Mute</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="RaidMax.IW4MAdmin.SharedLibraryCore" Version="2026.1.6.1" PrivateAssets="All" />
    </ItemGroup>

</Project>
