@echo off

ECHO "Pluto T4"
xcopy /y .\GameInterface\_integration_base.gsc      "%LOCALAPPDATA%\Plutonium\storage\t4\raw\scripts"
xcopy /y .\GameInterface\_integration_shared.gsc    "%LOCALAPPDATA%\Plutonium\storage\t4\raw\scripts"
xcopy /y .\GameInterface\_integration_utility.gsh   "%LOCALAPPDATA%\Plutonium\storage\t4\raw\scripts"
xcopy /y .\GameInterface\_integration_t4.gsc        "%LOCALAPPDATA%\Plutonium\storage\t4\raw\scripts\mp"
xcopy /y .\GameInterface\_integration_t4zm.gsc      "%LOCALAPPDATA%\Plutonium\storage\t4\raw\scripts\sp"
xcopy /y .\ZombieStats\_zm_stats_t4.gsc             "%LOCALAPPDATA%\Plutonium\storage\t4\raw\scripts\sp"

ECHO "Pluto IW5"
xcopy /y .\GameInterface\_integration_base.gsc                          "%LOCALAPPDATA%\Plutonium\storage\iw5\scripts"
xcopy /y .\GameInterface\_integration_shared.gsc                        "%LOCALAPPDATA%\Plutonium\storage\iw5\scripts"
xcopy /y .\GameInterface\_integration_utility.gsh                       "%LOCALAPPDATA%\Plutonium\storage\iw5\scripts"
xcopy /y .\GameInterface\_integration_iw5.gsc                           "%LOCALAPPDATA%\Plutonium\storage\iw5\scripts"
xcopy /y .\AntiCheat\IW5\storage\iw5\scripts\_customcallbacks.gsc       "%LOCALAPPDATA%\Plutonium\storage\iw5\scripts\mp"

ECHO "Pluto T5"
xcopy /y .\GameInterface\_integration_base.gsc      "%LOCALAPPDATA%\Plutonium\storage\t5\scripts"
xcopy /y .\GameInterface\_integration_shared.gsc    "%LOCALAPPDATA%\Plutonium\storage\t5\scripts"
xcopy /y .\GameInterface\_integration_t5.gsc        "%LOCALAPPDATA%\Plutonium\storage\t5\scripts\mp"
xcopy /y .\GameInterface\_integration_t5zm.gsc      "%LOCALAPPDATA%\Plutonium\storage\t5\scripts\sp\zom"
xcopy /y .\ZombieStats\_zm_stats_t5.gsc             "%LOCALAPPDATA%\Plutonium\storage\t5\scripts\sp\zom"

ECHO "Pluto T6"
xcopy /y .\GameInterface\_integration_base.gsc                          "%LOCALAPPDATA%\Plutonium\storage\t6\scripts"
xcopy /y .\GameInterface\_integration_shared.gsc                        "%LOCALAPPDATA%\Plutonium\storage\t6\scripts"
xcopy /y .\GameInterface\_integration_t6.gsc                            "%LOCALAPPDATA%\Plutonium\storage\t6\scripts"
xcopy /y .\GameInterface\_integration_t6zm_helper.gsc                   "%LOCALAPPDATA%\Plutonium\storage\t6\scripts\zm"
xcopy /y .\ZombieStats\_zm_stats_t6.gsc                                 "%LOCALAPPDATA%\Plutonium\storage\t6\scripts\zm"
xcopy /y .\AntiCheat\PT6\storage\t6\scripts\mp\_customcallbacks.gsc     "%LOCALAPPDATA%\Plutonium\storage\t6\scripts\mp"
