<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>IW4MAdmin.Plugins.ZombieStats</RootNamespace>
        <PackageId>RaidMax.IW4MAdmin.Plugins.ZombieStats</PackageId>
        <Authors>RaidMax</Authors>
        <Company>Forever None</Company>
        <Product>Zombie Statistics</Product>
        <Description>Zombie Statistics Plugin for IW4MAdmin</Description>
        <Copyright>2026</Copyright>
        <Configurations>Debug;Release;Prerelease</Configurations>
        <LangVersion>Latest</LangVersion>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Data\Data.csproj" />
        <ProjectReference Include="..\..\SharedLibraryCore\SharedLibraryCore.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Abstractions\" />
      <Folder Include="Components\" />
    </ItemGroup>

</Project>
