<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ApplicationIcon/>
        <StartupObject/>
        <PackageId>RaidMax.IW4MAdmin.Plugins.Stats</PackageId>
        <Authors>RaidMax</Authors>
        <Company>Forever None</Company>
        <Product>Client Statistics</Product>
        <Description>Client Statistics Plugin for IW4MAdmin</Description>
        <Copyright>2018</Copyright>
        <Configurations>Debug;Release;Prerelease</Configurations>
        <LangVersion>Latest</LangVersion>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Data\Data.csproj" PrivateAssets="All" />
      <ProjectReference Include="..\..\SharedLibraryCore\SharedLibraryCore.csproj" PrivateAssets="All" />
    </ItemGroup>


</Project>
