<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Components\UI\" />
    </ItemGroup>

    <ItemGroup>
      <AdditionalFiles Include="Components\UI\Display\ColorCode.razor" />
      <AdditionalFiles Include="Components\UI\Display\Render.razor" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Data\Data.csproj" />
      <ProjectReference Include="..\SharedLibraryCore\SharedLibraryCore.csproj" />
    </ItemGroup>

</Project>
