<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Configurations>Debug;Release;Prerelease</Configurations>
        <Platforms>AnyCPU</Platforms>
        <Title>RaidMax.IW4MAdmin.Data</Title>
        <Version>1.0.0.0</Version>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.0"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles</IncludeAssets>
        </PackageReference>

        <PackageReference Include="Npgsql" Version="9.0.0"/>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.0"/>

        <!-- This fuckin' ugly piece of shit package - TODO: Remove it. PostgreSQL Supremacy -->
        <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.0"/>
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="Migrations\MySql\20260210135942_AddServerActivityStats.cs" />
      <Compile Remove="Migrations\MySql\20260210135942_AddServerActivityStats.Designer.cs" />
    </ItemGroup>

</Project>