<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Plugins\AutomessageFeed\AutomessageFeed.csproj" ReferenceOutputAssembly="false" Private="false" />
      <ProjectReference Include="..\Plugins\LiveRadar\LiveRadar.csproj" ReferenceOutputAssembly="false" Private="false" />
      <ProjectReference Include="..\Plugins\Login\Login.csproj" ReferenceOutputAssembly="false" Private="false" />
      <ProjectReference Include="..\Plugins\Mute\Mute.csproj" ReferenceOutputAssembly="false" Private="false" />
      <ProjectReference Include="..\Plugins\ProfanityDeterment\ProfanityDeterment.csproj" ReferenceOutputAssembly="false" Private="false" />
      <ProjectReference Include="..\Plugins\Stats\Stats.csproj" ReferenceOutputAssembly="false" Private="false" />
      <ProjectReference Include="..\Plugins\Welcome\Welcome.csproj" ReferenceOutputAssembly="false" Private="false" />
    </ItemGroup>

</Project>
