<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Plugins\AutomessageFeed\AutomessageFeed.csproj" />
      <ProjectReference Include="..\Plugins\LiveRadar\LiveRadar.csproj" />
      <ProjectReference Include="..\Plugins\Login\Login.csproj" />
      <ProjectReference Include="..\Plugins\Mute\Mute.csproj" />
      <ProjectReference Include="..\Plugins\ProfanityDeterment\ProfanityDeterment.csproj" />
      <ProjectReference Include="..\Plugins\Stats\Stats.csproj" />
      <ProjectReference Include="..\Plugins\Welcome\Welcome.csproj" />
    </ItemGroup>

</Project>
