<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Integrations.SevenDaysToDie</AssemblyName>
    <RootNamespace>Integrations.SevenDaysToDie</RootNamespace>
    <Configurations>Debug;Release;Prerelease</Configurations>
    <Platforms>AnyCPU</Platforms>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Prerelease' ">
    <Optimize>true</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Data\Data.csproj" />
    <ProjectReference Include="..\..\SharedLibraryCore\SharedLibraryCore.csproj" />
  </ItemGroup>

</Project>
